apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:22b0a110b9e1b4ea2e854e9fd7e7f498ec7ad015563726bc4b466ca37361e278
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
