apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:2f6f1e1ec60323eeb92d85ec1ddd42ed4296ff57bf45d215784e07c7820f3a96
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
