apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:384124435b154fe36502799b9f21ed84625368c69e1f8f5f4eca470e186ebf06
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
