apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:57741e6335c0f74864a8d0d1333b54081ff237d62d23539788003d1590f5b176
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
