apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:d689e3bb5cf3c2416b49d87a105c23ba831d7e4f7faaa57f11e817ff19a27193
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
