apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:1ec98410f656f1c17a2e79f7832abfffedc1672ea651d6990683bf97e97f6bbd
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
