apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:b983942c106f1b01af9da2aab3128e51a26987bf6c44ce7d89936f343b9a5799
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
