apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- name: kustomizeoverride
  newName: ghcr.io/yogstation13/yogbot-kt
  newTag: master-e5835d8cff04c0ba56d55c876b815aedf165d1d9 
