apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:5c4584d3732df3e4a0a53ddd889fd4908432e2d4dce9c4a07b4df87fe94999ab
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
