apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- name: kustomizeoverride
  newName: ghcr.io/yogstation13/yogbot-kt
  newTag: master-e05e60b222563b37a9744cd28a4747e7b2eacd5a
