apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:2085d0fdd20bb85613cfe4d19bc5f56b89612fccf207e631be4a392dd505d204
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
