apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:0f954a8edbb1086e3d39249bcb530a1683d270fb835778daded98f3ac0278f12
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
