apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:4b17d9f3f25d5a36364e6ffceabb9fb280fd113e2b91b90748c935ae657200c3
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
