apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- name: kustomizeoverride
  newName: ghcr.io/yogstation13/yogbot-kt
  newTag: empty-commit-02ca3456c46cef24ae56aea683d71c628ee1c4de
