apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:39332b028b6dbb60afbda63723e4876fcc5103a23d086a84b511fc38844f9c30
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
