apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:e4cc01aeaeeb1aed267a0d791ee3e1445544c021a3be77aaddb3f9ce640757f6
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
