apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomization/inflated.yaml
images:
- digest: sha256:85f1bf7f9cd538ea2be0aa43b78c5730f1cfd9753e085220bf632f158bc3f927
  name: kustomizeoverride
  newName: harbor.yogstation.net/yogstation/yogbotkt
