apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "yogbot-kt.fullname" . }}
  labels:
    {{- include "yogbot-kt.labels" . | nindent 4 }}
data:
{{ list .Values.config "yogbot" | include "yogbot-kt.recurseFlattenMap" | indent 2 }}
{{- if .Values.configFlat }}
{{ toYaml .Values.configFlat | indent 2 }}
{{- end }}