apiVersion: v1
kind: Secret
metadata:
  name: {{ template "yogbot-kt.fullname" . }}
  labels:
    {{- include "yogbot-kt.labels" . | nindent 4 }}
type: Opaque
stringData:
{{ list .Values.secrets "yogbot" | include "yogbot-kt.recurseFlattenMap" | indent 2 }}
{{- if .Values.secretsFlat }}
{{ toYaml .Values.secretsFlat | indent 2 }}
{{- end }}