apiVersion: v1
kind: Secret
metadata:
  name: {{ template "yogbot-kt.fullname" . }}
  labels:
    {{- include "yogbot-kt.labels" . | nindent 4 }}
type: Opaque
stringData: {{list .Values.secrets "yogbot" | include "yogbot-kt.recurseFlattenMap" | nindent 2}}